### ISSUE TITLE
scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.

### ISSUE THREAD

**Issue by hwxy233** [zjffdu/flink-sql-cook-on-zeppelin#10]
我使用`docker-compose`启动后，执行一个例子时会遇到这个报错,我试了几个例子的`create`语句都会有报错。
完整报错如下:
```java
org.apache.zeppelin.interpreter.InterpreterException: org.apache.zeppelin.interpreter.InterpreterException: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:76)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:836)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:744)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:172)
	at org.apache.zeppelin.scheduler.AbstractScheduler.runJob(AbstractScheduler.java:132)
	at org.apache.zeppelin.scheduler.ParallelScheduler.lambda$runJobInScheduler$0(ParallelScheduler.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.zeppelin.interpreter.InterpreterException: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:76)
	at org.apache.zeppelin.interpreter.Interpreter.getInterpreterInTheSameSessionByClassName(Interpreter.java:355)
	at org.apache.zeppelin.interpreter.Interpreter.getInterpreterInTheSameSessionByClassName(Interpreter.java:366)
	at org.apache.zeppelin.flink.FlinkStreamSqlInterpreter.open(FlinkStreamSqlInterpreter.java:47)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:70)
	... 8 more
Caused by: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
	at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
	at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1390)
	at scala.tools.nsc.Global$Run.<init>(Global.scala:1242)
	at scala.tools.nsc.interpreter.IMain.compileSourcesKeepingRun(IMain.scala:439)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compileAndSaveRun(IMain.scala:862)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:820)
	at scala.tools.nsc.interpreter.IMain.bind(IMain.scala:682)
	at scala.tools.nsc.interpreter.IMain.bind(IMain.scala:719)
	at scala.tools.nsc.interpreter.IMain.bind(IMain.scala:720)
	at org.apache.zeppelin.flink.FlinkScalaInterpreter$$anonfun$createFlinkILoop$1.apply(FlinkScalaInterpreter.scala:319)
	at org.apache.zeppelin.flink.FlinkScalaInterpreter$$anonfun$createFlinkILoop$1.apply(FlinkScalaInterpreter.scala:317)
	at scala.tools.nsc.interpreter.IMain.beQuietDuring(IMain.scala:221)
	at org.apache.zeppelin.flink.FlinkScalaInterpreter.createFlinkILoop(FlinkScalaInterpreter.scala:317)
	at org.apache.zeppelin.flink.FlinkScalaInterpreter.open(FlinkScalaInterpreter.scala:113)
	at org.apache.zeppelin.flink.FlinkInterpreter.open(FlinkInterpreter.java:65)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:70)
	... 12 more
```

![image](https://user-images.githubusercontent.com/22147612/130729537-fbd33f37-5adc-49b8-84e8-e99852c87e4a.png)

我看了下`docker`容器的`java`版本，scala没有找到这个是正常的吗:

![image](https://user-images.githubusercontent.com/22147612/130729289-be71b99a-62ba-4bee-b36a-3a18ae01a7b4.png)

`docker-compose`文件:

```docker
version: "3.4"

services:
  zeppelin:
    image: apache/zeppelin:0.9.0
    volumes:
      - ./logs:/logs
      - .:/notebook
      - ~/Documents/ps/codes/flink/flink-1.12.1:/flink
    environment:
      EPPELIN_LOG_DIR: /logs
      ZEPPELIN_NOTEBOOK_DIR: /notebook
    ports:
    - 8080:8080
    - 8081:8081
```
只修改了`flink`的路径，`flink`使用的是`flink-1.12.1-bin-scala_2.11.tgz`

`docker info | grep Registry`:

![image](https://user-images.githubusercontent.com/22147612/130730750-24593d30-3038-4a20-9674-80e4fe06b801.png)

`docker images`

![image](https://user-images.githubusercontent.com/22147612/130731162-36e75b95-75ea-4ea2-9de0-b721f3dd9844.png)

**Comment by zjffdu** [comment]
用最新的0.10试试，这是最新文档 https://www.yuque.com/jeffzhangjianfeng/gldg8w/yfsiwy

**Comment by hwxy233** [comment]
> 用最新的0.10试试，这是最新文档 https://www.yuque.com/jeffzhangjianfeng/gldg8w/yfsiwy
嗯，zeppelin使用0.10，flink使用1.13版本可以运行了，感谢
