### ISSUE TITLE
为了使用 scala 2.12 版的flink ，zeppelin0.10 遇到问题

### ISSUE THREAD

**Issue by mullerhai** [zjffdu/flink-sql-cook-on-zeppelin#11]
env：

jdk 11

scala 2.12.12 Scala 2.12.12 (Eclipse OpenJ9 VM, Java 11.0.10)

flink   flink-1.13.2-bin-scala_2.12.tgz 

zeppelin 0.10 

when I use flink interpreter meet some error ,I have see the flink interpreter demon process is running ,but when I run the scala -flink mode   tell me  can not open flink interpreter ,feel  confused ,

 

I just import some flink dependency

```

import org.apache.flink.api.common.typeinfo.Types
import org.apache.flink.api.java.typeutils._
import org.apache.flink.api.scala.typeutils._
import org.apache.flink.api.scala._
import org.apache.flink.streaming.api.scala.{DataStream, StreamExecutionEnvironment}
import org.apache.flink.table.api.{DataTypes, EnvironmentSettings}
import org.apache.flink.table.api.bridge.scala.StreamTableEnvironment
import org.apache.flink.table.descriptors.{Csv, FileSystem, Schema}
import org.apache.flink.table.factories.TableSourceFactory

```

 

```

org.apache.zeppelin.interpreter.InterpreterException: org.apache.zeppelin.interpreter.InterpreterException: Fail to open FlinkInterpreter at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:76) at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:833) at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:741) at org.apache.zeppelin.scheduler.Job.run(Job.java:172) at org.apache.zeppelin.scheduler.AbstractScheduler.runJob(AbstractScheduler.java:132) at org.apache.zeppelin.scheduler.FIFOScheduler.lambda$runJobInScheduler$0(FIFOScheduler.java:42) at org.apache.zeppelin.scheduler.FIFOScheduler$$Lambda$337/0x0000000000000000.run(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:836) Caused by: org.apache.zeppelin.interpreter.InterpreterException: Fail to open FlinkInterpreter at org.apache.zeppelin.flink.FlinkInterpreter.open(FlinkInterpreter.java:80) at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:70) ... 9 more Caused by: java.lang.IllegalArgumentException: argument type mismatch at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) at org.apache.zeppelin.flink.FlinkInterpreter.loadFlinkScalaInterpreter(FlinkInterpreter.java:98) at org.apache.zeppelin.flink.FlinkInterpreter.open(FlinkInterpreter.java:74) ... 10 more

```

(base) [root@centos data]# ps -ef |grep flink
root 3778 3545 1 18:10 pts/1 00:00:07 /data/jdk11/bin/java -Dfile.encoding=UTF-8 -Dlog4j.configuration=file:///data/model/zeppelin-0.10.0-bin-all/conf/log4j.properties -Dlog4j.configurationFile=file:///data/model/zeppelin-0.10.0-bin-all/conf/log4j2.properties -Dzeppelin.log.file=/data/model/zeppelin-0.10.0-bin-all/logs/zeppelin-interpreter-flink-shared_process-root-centos.log -Xmx1024m -cp :/data/model/zeppelin-0.10.0-bin-all/local-repo/flink/*:/data/flink/lib/log4j-slf4j-impl-2.12.1.jar:/data/flink/lib/log4j-core-2.12.1.jar:/data/flink/lib/log4j-api-2.12.1.jar:/data/flink/lib/log4j-1.2-api-2.12.1.jar:/data/flink/lib/flink-table-blink_2.12-1.13.2.jar:/data/flink/lib/flink-table_2.12-1.13.2.jar:/data/flink/lib/flink-shaded-zookeeper-3.4.14.jar:/data/flink/lib/flink-json-1.13.2.jar:/data/flink/lib/flink-dist_2.12-1.13.2.jar:/data/flink/lib/flink-csv-1.13.2.jar:::/data/model/zeppelin-0.10.0-bin-all/interpreter/zeppelin-interpreter-shaded-0.10.0.jar:/data/flink/opt/flink-python_2.12-1.13.2.jar:/data/model/zeppelin-0.10.0-bin-all/interpreter/flink/zeppelin-flink-0.10.0-2.12.jar org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer 125.94.240.172 21116 flink-shared_process :
root 21696 49209 0 18:21 pts/1 00:00:00 grep --color=auto flink
root 34191 1 1 17:17 pts/0 00:00:48 /data/jdk11/bin/java -Xmx1073741824 -Xms1073741824 -XX:MaxMetaspaceSize=268435456 -Dlog.file=/data/flink/log/flink-root-standalonesession-6-centos.log -Dlog4j.configuration=file:/data/flink/conf/log4j.properties -Dlog4j.configurationFile=file:/data/flink/conf/log4j.properties -Dlogback.configurationFile=file:/data/flink/conf/logback.xml -classpath /data/flink/lib/flink-csv-1.13.2.jar:/data/flink/lib/flink-json-1.13.2.jar:/data/flink/lib/flink-shaded-zookeeper-3.4.14.jar:/data/flink/lib/flink-table_2.12-1.13.2.jar:/data/flink/lib/flink-table-blink_2.12-1.13.2.jar:/data/flink/lib/log4j-1.2-api-2.12.1.jar:/data/flink/lib/log4j-api-2.12.1.jar:/data/flink/lib/log4j-core-2.12.1.jar:/data/flink/lib/log4j-slf4j-impl-2.12.1.jar:/data/flink/lib/flink-dist_2.12-1.13.2.jar::: org.apache.flink.runtime.entrypoint.StandaloneSessionClusterEntrypoint --configDir /data/flink/conf --executionMode cluster -D jobmanager.memory.off-heap.size=134217728b -D jobmanager.memory.jvm-overhead.min=201326592b -D jobmanager.memory.jvm-metaspace.size=268435456b -D jobmanager.memory.heap.size=1073741824b -D jobmanager.memory.jvm-overhead.max=201326592b
root 34563 1 1 17:17 pts/0 00:00:45 /data/jdk11/bin/java -XX:+UseG1GC -Xmx536870902 -Xms536870902 -XX:MaxDirectMemorySize=268435458 -XX:MaxMetaspaceSize=268435456 -Dlog.file=/data/flink/log/flink-root-taskexecutor-6-centos.log -Dlog4j.configuration=file:/data/flink/conf/log4j.properties -Dlog4j.configurationFile=file:/data/flink/conf/log4j.properties -Dlogback.configurationFile=file:/data/flink/conf/logback.xml -classpath /data/flink/lib/flink-csv-1.13.2.jar:/data/flink/lib/flink-json-1.13.2.jar:/data/flink/lib/flink-shaded-zookeeper-3.4.14.jar:/data/flink/lib/flink-table_2.12-1.13.2.jar:/data/flink/lib/flink-table-blink_2.12-1.13.2.jar:/data/flink/lib/log4j-1.2-api-2.12.1.jar:/data/flink/lib/log4j-api-2.12.1.jar:/data/flink/lib/log4j-core-2.12.1.jar:/data/flink/lib/log4j-slf4j-impl-2.12.1.jar:/data/flink/lib/flink-dist_2.12-1.13.2.jar::: org.apache.flink.runtime.taskexecutor.TaskManagerRunner --configDir /data/flink/conf -D taskmanager.memory.network.min=134217730b -D taskmanager.cpu.cores=1.0 -D taskmanager.memory.task.off-heap.size=0b -D taskmanager.memory.jvm-metaspace.size=268435456b -D external-resources=none -D taskmanager.memory.jvm-overhead.min=201326592b -D taskmanager.memory.framework.off-heap.size=134217728b -D taskmanager.memory.network.max=134217730b -D taskmanager.memory.framework.heap.size=134217728b -D taskmanager.memory.managed.size=536870920b -D taskmanager.memory.task.heap.size=402653174b -D taskmanager.numberOfTaskSlots=1 -D taskmanager.memory.jvm-overhead.max=201326592b

**Comment by zjffdu** [comment]
It looks like jdk issue,  Could you try jdk 8 ? Zeppelin is built with JDK 8
```
9 more Caused by: java.lang.IllegalArgumentException: argument type mismatch at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at java.base/jdk.in
```
