### ISSUE TITLE
版本一致，使用公众号上的教程搭建报错如下，恳请解惑．

### ISSUE THREAD

**Issue by tangyuxiaoyao** [zjffdu/flink-sql-cook-on-zeppelin#2]
%flink.ssql

DROP TABLE IF EXISTS orders;

CREATE TABLE orders (
    order_uid  BIGINT,
    product_id BIGINT,
    price      DOUBLE,
    order_time TIMESTAMP(3)
) WITH (
    'connector' = 'datagen'
);

org.apache.zeppelin.interpreter.InterpreterException: org.apache.zeppelin.interpreter.InterpreterException: java.lang.NoSuchMethodError: org.apache.flink.api.common.ExecutionConfig.disableSysoutLogging()Lorg/apache/flink/api/common/ExecutionConfig;
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:76)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:760)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:668)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:172)
	at org.apache.zeppelin.scheduler.AbstractScheduler.runJob(AbstractScheduler.java:130)
	at org.apache.zeppelin.scheduler.ParallelScheduler.lambda$runJobInScheduler$0(ParallelScheduler.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.zeppelin.interpreter.InterpreterException: java.lang.NoSuchMethodError: org.apache.flink.api.common.ExecutionConfig.disableSysoutLogging()Lorg/apache/flink/api/common/ExecutionConfig;
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:76)
	at org.apache.zeppelin.interpreter.Interpreter.getInterpreterInTheSameSessionByClassName(Interpreter.java:355)
	at org.apache.zeppelin.interpreter.Interpreter.getInterpreterInTheSameSessionByClassName(Interpreter.java:366)
	at org.apache.zeppelin.flink.FlinkStreamSqlInterpreter.open(FlinkStreamSqlInterpreter.java:47)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:70)
	... 8 more
Caused by: java.lang.NoSuchMethodError: org.apache.flink.api.common.ExecutionConfig.disableSysoutLogging()Lorg/apache/flink/api/common/ExecutionConfig;
	at org.apache.zeppelin.flink.FlinkScalaInterpreter.setTableEnvConfig(FlinkScalaInterpreter.scala:444)
	at org.apache.zeppelin.flink.FlinkScalaInterpreter.open(FlinkScalaInterpreter.scala:114)
	at org.apache.zeppelin.flink.FlinkInterpreter.open(FlinkInterpreter.java:67)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:70)
	... 12 more
ERROR   
Took 15 sec. Last updated by anonymous at March 09 2021, 9:18:28 AM.

**Comment by zjffdu** [comment]
你用的docker image应该是版本老的，0.9.0 的docker image更新过，你把本地的删了，重新下载下

**Comment by tangyuxiaoyao** [comment]
已重新下载还是如上的错误．

**Comment by zjffdu** [comment]
看看docker image id是1672c2a624fb 吗？

**Comment by haydenzhourepo** [comment]
remove your proxy of docker registry，and reload your docker engine。 remove local zeppelin docker image， then pull again will fix this problem。 I have tried this way and set it up successfully.

**Comment by tangyuxiaoyao** [comment]
谢谢支持，已解决．

**Comment by alohahahaha** [comment]
> 谢谢支持，已解决．

请问您是如何解决的？
